// Code generated by "stringer -type=FileType"; DO NOT EDIT.

package jsonfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FTNull-0]
	_ = x[FTBool-1]
	_ = x[FTInt-2]
	_ = x[FTFloat-3]
	_ = x[FTString-4]
}

const _FileType_name = "FTNullFTBoolFTIntFTFloatFTString"

var _FileType_index = [...]uint8{0, 6, 12, 17, 24, 32}

func (i FileType) String() string {
	if i >= FileType(len(_FileType_index)-1) {
		return "FileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}
